dist: trusty
sudo: required
language: rust
cache:
    cargo: true
rust:
  - nightly
  - beta
  - stable
addons:
  apt:
    packages:
      - liborc-0.4-dev
      - libglib2.0-dev
      - libxml2-dev
      - libgtk-3-dev
matrix:
  allow_failures:
    - rust: stable
script:
    - rustc --version
    - cargo build
    - cargo build --all-features
before_install:
    - curl -L https://people.freedesktop.org/~slomo/gstreamer.tar.gz | tar xz
    - sed -i "s;prefix=/root/gstreamer;prefix=$PWD/gstreamer;g" $PWD/gstreamer/lib/pkgconfig/*.pc
    - export PKG_CONFIG_PATH=$PWD/gstreamer/lib/pkgconfig
    - export GST_PLUGIN_SYSTEM_PATH=$PWD/gstreamer/lib/gstreamer-1.0
    - export GST_PLUGIN_SCANNER=$PWD/gstreamer/libexec/gstreamer-1.0/gst-plugin-scanner
    - export PATH=$PATH:$PWD/gstreamer/bin
    - export LD_LIBRARY_PATH=$PWD/gstreamer/lib:$LD_LIBRARY_PATH
