[package]
name = "media-toc"
version = "0.3.1"
authors = ["François Laignel <fengalin@free.fr>"]
keywords = ["multimedia", "chapter", "table-of-contents", "gtk3", "gstreamer"]
repository = "https://github.com/fengalin/media-toc"
readme = "README.md"
description = "Build a table of contents from a media file or split a media file into chapters"
license = "MIT"
build = "build.rs"

[dependencies]
cairo-rs = "0.4"
clap = "^2"
byteorder = "^1"
chrono = "^0"
gdk = "0.8"
glib = "0.5"
gstreamer = { version = "0.11", features = ["v1_10"] }
gstreamer-audio = { version = "0.11", features = ["v1_10"] }
gtk = { version = "0.4", features = ["v3_18"] }
image = "^0"
lazy_static = "^0"
pango = "0.4"
sample = "^0"

gettext-rs = { git = "https://github.com/Koka/gettext-rs", features = ["gettext-system"] }
#gettext-rs = { git = "https://github.com/fengalin/gettext-rs", features = ["gettext-system"] }
#gettext-rs = { path = "../gettext-rs", features = ["gettext-system"] }

[features]
dump-waveform = ["cairo-rs/png"]
profiling-audio-draw = []
profiling-audio-buffer = []
profile-waveform-image = []
trace-audio-buffer = []
trace-audio-caps = []
trace-audio-controller = []
trace-main-controller = []
trace-playback-queues = []
trace-waveform-buffer = []
trace-waveform-rendering = []
trace-chapters-boundaries = []
default-features = []

[dev-dependencies]
cairo-rs = { version = "0.4", features = ["png"] }
