[package]
name = "media-toc"
version = "0.1.0"
authors = ["fengalin <fengalin@free.fr>"]

[dependencies]
byte-slice-cast = "^0"
chrono = "^0"
image = "^0"
url = "^1"

#cairo-rs = { git = "https://github.com/gtk-rs/cairo.git" }
cairo-rs = { path = "../cairo" }
#gtk = { git = "https://github.com/gtk-rs/gtk.git", features = ["v3_18"] }
gtk = { path = "../gtk", features = ["v3_18"] }
#glib = { git = "https://github.com/gtk-rs/glib.git" }
glib = { path = "../glib" }

#gstreamer = { git = "https://github.com/sdroege/gstreamer-rs.git", features = ["v1_10"] }
#gstreamer-audio = { git = "https://github.com/sdroege/gstreamer-rs.git", features = ["v1_10"] }
#gstreamer-app = { git = "https://github.com/sdroege/gstreamer-rs.git", features = ["v1_10"] }

gstreamer = { path = "../gstreamer-rs/gstreamer", features = ["v1_10"] }
gstreamer-audio = { path = "../gstreamer-rs/gstreamer-audio", features = ["v1_10"] }
gstreamer-app = { path = "../gstreamer-rs/gstreamer-app", features = ["v1_10"] }

[features]
audio-draw-profiling = []
default-features = []
