[package]
name = "media-toc"
version = "0.1.0"
authors = ["fengalin <fengalin@free.fr>"]

[dependencies]
cairo-rs = { git = "https://github.com/gtk-rs/cairo.git" }
gtk = { git = "https://github.com/gtk-rs/gtk.git", features = ["v3_18"] }
glib = { git = "https://github.com/gtk-rs/glib.git" }
chrono = "^0"
url = "^1"
image = "^0"

[dependencies.gstreamer]
git = "https://github.com/fengalin/gstreamer-rs.git"
features = ["v1_10"]
