[package]
name = "media-toc"
version = "0.2.0"
authors = ["fengalin <fengalin@free.fr>"]

[dependencies]
byte-slice-cast = "^0"
chrono = "^0"
image = "^0"
lazy_static = "^0"

cairo-rs = { git = "https://github.com/gtk-rs/cairo.git" }
gtk = { git = "https://github.com/gtk-rs/gtk.git", features = ["v3_10"] }
glib = { git = "https://github.com/gtk-rs/glib.git" }

gstreamer = { git = "https://github.com/sdroege/gstreamer-rs.git" }
gstreamer-audio = { git = "https://github.com/sdroege/gstreamer-rs.git" }
gstreamer-app = { git = "https://github.com/sdroege/gstreamer-rs.git" }

[features]
dump-waveform = ["cairo-rs/png"]
profiling-audio-draw = []
profiling-audio-buffer = []
profiling-tracker = []
profile-waveform-image = []
trace-audio-buffer = []
trace-audio-caps = []
trace-audio-queue = []
trace-audio-controller = []
trace-main-controller = []
trace-waveform-buffer = []
trace-waveform-rendering = []
default-features = []

[dev-dependencies]
byteorder = "1"
cairo-rs = { git = "https://github.com/gtk-rs/cairo.git", features = ["png"] }
