[package]
name = "media-toc"
version = "0.1.0"
authors = ["fengalin <fengalin@free.fr>"]

[dependencies]
gtk = { git = "https://github.com/gtk-rs/gtk.git", features = ["v3_18"] }
cairo-rs = { git = "https://github.com/gtk-rs/cairo.git" }
gstreamer = { git = "https://github.com/sdroege/gstreamer-rs.git" }
chrono = "^0"
